#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔥 Pre-commit hook is running!"

# Check if kms CLI is installed
if ! command -v kms >/dev/null 2>&1; then
    echo "\nError: KMS CLI (kms) is not installed. Please install the KMS CLI before committing.\n You can refer to the documentation at https://kms.hanzo.ai/docs/cli/overview\n\n"
    exit 1
fi

kms scan git-changes --staged -v
